[package]
name = "serde-path"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.219"

[dev-dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140", features = ["raw_value"] }
